Updated readme and other files
ihdia/Palmira pull request #1
Opened 2021-05-14 13:55 UTC by SowmyaAitha

Updated readme and few other files

2021-05-14 14:14 UTC, Syzygianinfern0 requested changes
We can remove the `region_data.json` files and release them along with the dataset download link.
Also, rename the `readme.txt` under the `images` folder to `README.md`.

2021-05-14 14:32 UTC, SowmyaAitha commented
Made required changes

2021-05-14 14:32 UTC, Syzygianinfern0 commented
> We can remove the `region_data.json` files and release them along with the dataset download link.
> Also, rename the `readme.txt` under the `images` folder to `README.md`.

2021-05-15 13:55 UTC, Syzygianinfern0 approved these changes

2021-05-15 13:57 UTC, merged